# Generated by Django 5.2.7 on 2025-10-04 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountModel',
            new_name='Account',
        ),
        migrations.RenameModel(
            old_name='ProjectCodeModel',
            new_name='ProjectCode',
        ),
        migrations.RenameModel(
            old_name='TransactionModel',
            new_name='Transaction',
        ),
    ]
