[project]
name = "finance"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "crispy-bootstrap5>=2025.6",
    "django>=5.2.7",
    "django-crispy-forms>=2.4",
    "django-json-widget>=2.0.4",
]
